name:                Compiler
version:             0.1.0.0
github:              "RichardBlazek/Compiler"
license:             MIT
author:              "Richard Blažek"
maintainer:          "blazek.risa@gmail.com"
copyright:           "2021 Richard Blažek"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/RichardBlazek/Compiler>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.2.1

library:
  source-dirs: src

executables:
  Compiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Compiler

tests:
  Compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Compiler
    - HUnit >= 1.6 && < 2.0
