name:                Compiler
version:             0.1.0.0
github:              "RichardBlazek/Compiler"
license:             MIT
author:              "Richard Blažek"
maintainer:          "blazek.risa@gmail.com"
copyright:           "2021 Richard Blažek"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/RichardBlazek/Compiler>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.2.1
- mtl >= 2.2.2
- http-conduit >= 2.3.8
- text >= 1.2.4.1
- filepath >= 1.4.2.1

library:
  source-dirs: src

executables:
  Compiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Compiler
