# Documentation: https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/5.yaml

packages:
- .
